---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-dhcp-cni-ds
  namespace: kube-system
  labels:
    tier: node
    app: dhcp-cni
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: dhcp-cni
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: kube-dhcp-cni
        image: mellanox/dhcp-cni
        securityContext:
          privileged: true
        command:
        - /bin/sh
        args:
        - -c
        - 'rm -f /run/cni/dhcp.sock; cp -f /dhcp /host/optcnibin/; exec /dhcp daemon'
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        volumeMounts:
        - name: run
          mountPath: /run
        - name: optcnibin
          mountPath: /host/optcnibin
      volumes:
        - name: run
          hostPath:
            path: /run
        - name: optcnibin
          hostPath:
            path: /opt/cni/bin            
