---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-dhcp-cni-ds
  namespace: kube-system
  labels:
    tier: node
    app: dhcp-cni
spec:
  template:
    metadata:
      labels:
        tier: node
        app: dhcp-cni
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: kube-dhcp-cni
        image: mellanox/dhcp-cni:latest
        securityContext:
          privileged: true
        command:
        - /bin/sh
        args:
        - -c
        - 'rm -f /run/cni/dhcp.sock; exec /dhcp daemon'
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        volumeMounts:
        - name: run
          mountPath: /run
      volumes:
        - name: run
          hostPath:
            path: /run
